### ISSUE TITLE
Make it harder for pipelines to tread on each others' feet

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pydpiper#164]
Several pipelines were started in the same directory but with different uri files.  There are various (potential) problems here including the completed stage log and various output files being clobbered, but some servers also believed that their executors had crashed - unsure if this is related.  (We've increased the allowed latency and may at some point revert this?)

At any rate, it might be worthwhile to make it harder for this sort of problem to occur, e.g., making more prominent warnings not to do this, timestamping the directories that are created, putting some sort of lock file in the pydpiper current working directory, etc.

The executor logs show something like this:

    Exception in thread Thread-5:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 504, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/axiom2/projects/matthijs/2014-12-Lily-bootstrap/python/pydpiper-1.10-py2.7.egg/EGG-INFO/scripts/pipeline_executor.py", line 417, in heartbeat
        self.pyro_proxy_for_server.updateClientTimestamp(self.clientURI)
      File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 168, in __call__
        return self.__send(self.__name, args, kwargs)
      File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 370, in _pyroInvoke
        raise data
    KeyError: u'PYRO:obj_fe2a79587946439b87920598da659a88@172.16.1.19:53812'

    Exception in thread Thread-6:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 504, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 839, in shutdown_thread
        self.close()
      File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 1076, in close
        self.transportServer.close()
      File "/usr/local/lib/python2.7/dist-packages/Pyro4/socketserver/multiplexserver.py", line 117, in close
        for c in self.clients:
    RuntimeError: Set changed size during iteration

The first traceback is something we've seen before when the distributed Pydpiper state becomes inconsistent (due to network issues, etc.) and isn't necessarily fatal in itself although it may cause the server to stop launching new executors, but the second is entirely inside Pyro ... unsure if this is a possible symptom of the problem.  In general, many Pydpiper servers may be running on a system. Other than the URI files, it's not clear to me how these particular instances might be interfering with each other merely by being run in the same directory.

**Comment by bcdarwin** [comment]
Basically fixed except for logs; see #189.
