### ISSUE TITLE
"Couldn't determine remaining walltime from qstat call" and Traceback on SGE executors from pydpiper-1.11

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#167]
[2015-01-16 10:42:23.595,Pyro4,INFO] Pyro log configured using built-in defaults, level=INFO
[2015-01-16 10:42:23.852,pydpiper.application,INFO] Calling `start`
[2015-01-16 10:42:23.861,pydpiper.application,INFO] Command is: /opt/quarantine/pydpiper/1.11/build/bin/MBM.py --queue=sge --num-executors=60 --proc=1 --mem=2 --verbose --pipeline-name=male-and-female-raw --lsq6-large-rotations --registration-method=mincANTS --calc-stats --bootstrap ../subjects/B1AFISP.mnc ../subjects/B1BFISP.mnc ../subjects/B2AFISP.mnc ../subjects/B2BFISP.mnc ../subjects/B3AFISP.mnc ../subjects/B3BFISP.mnc ../subjects/B4AFISP.mnc ../subjects/B5BFISP.mnc ../subjects/B6AFISP.mnc ../subjects/B7AFISP.mnc ../subjects/B7BFISP.mnc ../subjects/B8AFISP.mnc ../subjects/B8BFISP.mnc ../subjects/RMS.20141213_MCH_RAt001_857_FISP.mnc ../subjects/RMS.20141213_MCH_RAt001_858_FISP.mnc ../subjects/RMS.20141213_MCH_RAt001_859_FISP.mnc ../subjects/RMS.20141213_MCH_RAt001_860_FISP.mnc ../subjects/RMS.20141213_MCH_RAt001_870_FISP.mnc ../subjects/RMS.20141213_MCH_RAt001_871_FISP.mnc ../subjects/RMS.20141213_MCH_RAt001_873_FISP.mnc ../subjects/RMS.20141213_MCH_RAt001_886_FISP.mnc ../subjects/RMS.20141213_MCH_RAt001_894_FISP.mnc ../subjects/RMS.20141213_MCH_RAt001_898_FISP.mnc
[2015-01-16 10:42:23.861,pydpiper.application,INFO] Command version : 1.11
[2015-01-16 10:42:24.011,atoms_and_modules.registration_functions,INFO] No mask directory specified as command line option. No masks included during RegistrationPipeFH initialization.
[2015-01-16 10:42:24.524,pydpiper.pipeline,INFO] Create Edges time: 0.0113670825958
[2015-01-16 10:42:24.535,pydpiper.pipeline,INFO] Graph heads: [0, 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93]
[2015-01-16 10:42:24.630,pydpiper.application,INFO] Starting pipeline daemon...
[2015-01-16 10:42:24.631,pydpiper.pipeline,INFO] Finished stages log doesn't exist or is corrupt.
[2015-01-16 10:42:24.633,Pyro4.multiplexserver,INFO] starting multiplexed socketserver
[2015-01-16 10:42:24.636,pydpiper.pipeline,INFO] Daemon is running at: 172.16.133.224:50712
[2015-01-16 10:42:24.637,pydpiper.pipeline,INFO] The pipeline's uri is: PYRO:obj_4d6d5dd1c38643a5ba0dc088ca67e88a@172.16.133.224:50712
[2015-01-16 10:42:24.640,Pyro4.core,INFO] daemon 172.16.133.224:50712 entering requestloop
[2015-01-16 10:42:24.639,pydpiper.pipeline,ERROR] Couldn't determine remaining walltime from qstat call
Traceback (most recent call last):
  File "/opt/quarantine/pydpiper/1.11/build/lib/python2.7/site-packages/pydpiper-1.11-py2.7.egg/pydpiper/pipeline.py", line 836, in launchServer
    jid    = os.environ["PBS_JOBID"]
  File "/opt/quarantine/anaconda/2.1.0/build/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'PBS_JOBID'
[2015-01-16 10:42:24.649,pydpiper.pipeline,INFO] Launching 47 executors
[2015-01-16 10:42:24.654,pydpiper.pipeline_executor,WARNING] --queue is deprecated; use --queue-type instead
[2015-01-16 10:42:24.656,pydpiper.pipeline_executor,WARNING] --queue is deprecated; use --queue-type instead
[2015-01-16 10:42:24.658,pydpiper.pipeline_executor,WARNING] --queue is deprecated; use --queue-type instead
[2015-01-16 10:42:24.658,pydpiper.pipeline_executor,WARNING] --queue is deprecated; use --queue-type instead

**Comment by bcdarwin** [comment]
The traceback isn't important ... I guess I should change this to an INFO instead of an ERROR.
