### ISSUE TITLE
LSQ6 module does not work when initial model dir contains `<...>_native.mnc` file but no `xfm` file

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pydpiper#173]
Such a configuration should supposedly be possible according to various code comments.  However, when a pipeline is started using an init-model in this configuration, regardless of other LSQ-specific options (a different traceback occurs when using current `master`, as the code incorrectly stops unwinding the stack and continues in a meaningless state):

```
Failed in putting together resample command; unexpected error:
Traceback (most recent call last):
  File "/axiom2/projects/bdarwin/pydpiper-testing/lib/python2.7/site-packages/pydpiper-1.11-py2.7.egg/EGG-INFO/scripts/MBM.py", line 154, in <module>
    application.start()
  File "/projects/souris/bdarwin/pydpiper-testing/lib/python2.7/site-packages/pydpiper-1.11-py2.7.egg/pydpiper/application.py", line 159, in start
    self.run()
  File "/axiom2/projects/bdarwin/pydpiper-testing/lib/python2.7/site-packages/pydpiper-1.11-py2.7.egg/EGG-INFO/scripts/MBM.py", line 77, in run
    options)
  File "/projects/souris/bdarwin/pydpiper-testing/lib/python2.7/site-packages/pydpiper-1.11-py2.7.egg/atoms_and_modules/LSQ6.py", line 282, in __init__
    self.setupPipeline()
  File "/projects/souris/bdarwin/pydpiper-testing/lib/python2.7/site-packages/pydpiper-1.11-py2.7.egg/atoms_and_modules/LSQ6.py", line 297, in setupPipeline
    lsq6module.finalize()
  File "/projects/souris/bdarwin/pydpiper-testing/lib/python2.7/site-packages/pydpiper-1.11-py2.7.egg/atoms_and_modules/LSQ6.py", line 1029, in finalize
    self.resampleInputFilesAndSetLastBasevol()
  File "/projects/souris/bdarwin/pydpiper-testing/lib/python2.7/site-packages/pydpiper-1.11-py2.7.egg/atoms_and_modules/LSQ6.py", line 999, in resampleInputFilesAndSetLastBasevol
    argArray=["-sinc"])
  File "/projects/souris/bdarwin/pydpiper-testing/lib/python2.7/site-packages/pydpiper-1.11-py2.7.egg/atoms_and_modules/minc_atoms.py", line 467, in __init__
    **kwargs)
  File "/projects/souris/bdarwin/pydpiper-testing/lib/python2.7/site-packages/pydpiper-1.11-py2.7.egg/atoms_and_modules/minc_atoms.py", line 574, in __init__
    self.outfile = self.setOutputFile(self.outputLocation, defaultDir)
  File "/projects/souris/bdarwin/pydpiper-testing/lib/python2.7/site-packages/pydpiper-1.11-py2.7.egg/atoms_and_modules/minc_atoms.py", line 616, in setOutputFile
    outBase = fh.removeBaseAndExtension(self.cxfm) + "-resampled.mnc"
  File "/projects/souris/bdarwin/pydpiper-testing/lib/python2.7/site-packages/pydpiper-1.11-py2.7.egg/pydpiper/file_handling.py", line 10, in removeBaseAndExtension
    bname = basename(filename)
  File "/usr/lib/python2.7/posixpath.py", line 112, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

The trouble here is that `rf.setInitialTarget` returns a tuple whose second element is the native target if it exists in the init model directory, otherwise the standard space target.  If an `xfm` is present, it becomes the native-space FH's last transform, while if no _native file is present, the returned target (being the standard space image) has a last transform of form `img.date._dist_corr_to_init_model_lsq6_k.xfm`.  Then construction of the appropriate `mincresample` calls `getLastXfm` on the handler, which, in our situation, has no previous transform and so various directory names cannot be chosen.  Some logic could be added to deal with filenames, but subsequent confusion might occur as well as suggested by various other LSQ6-related issues.

**Comment by bcdarwin** [comment]
More specifically, [here](https://github.com/Mouse-Imaging-Centre/pydpiper/blob/master/atoms_and_modules/registration_functions.py#L230) is the bug.

The [comments](https://github.com/Mouse-Imaging-Centre/pydpiper/blob/master/atoms_and_modules/registration_functions.py#L184-L198) above the code contradict the [wiki](https://wiki.mouseimaging.ca/display/MICePub/Using+or+Creating+an+Initial+Model) regarding whether such a configuration should even be possible.  Perhaps the best thing is to raise an exception and allow the user to supply their own transform (e.g., the identity transform if the files differ by cropping).

**Comment by bcdarwin** [comment]
Fix committed and wiki updated.
