### ISSUE TITLE
pydpiper on Scinet: race condition on job submission

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#201]
Running this command:
```
MAGeT.py --num-executors=50 \
    --verbose --pipeline-name=MAGET-full \
    --atlas-library ./MAGET-atlas \
    --mask \
    --lsq12-protocol=./default_linear_MAGeT_prot.csv \
	--nlin-protocol=./default_nlin_MAGeT_minctracc_prot.csv \
    --config-file /project/j/jlerch/matthijs/pydpiper_modules/pydpiper-master-v1.13.1/python/pydpiper-1.13.1-py2.7.egg/config/SciNet.cfg \
	$(cat random-filelist.txt)
```

Threw this error
```
Couldn't import dot_parser, loading of dot files will not be possible.
qsub -o MAGeT.py-pipeline-20150330-102424491558.job-o.log -e MAGeT.py-pipeline-20150330-102424491558.job-e.log -V /home/m/mchakrav/gumae/pbs-jobs/MAGeT.py-pipeline-20150330-102424491558.job
27976493.gpc-sched-ib0
Submitted!
qsub -o MAGeT.py-executor-1-20150330-102518068191.job-o.log -e MAGeT.py-executor-1-20150330-102518068191.job-e.log -V -Wdepend=after:27976493.gpc-sched-ib0 /home/m/mchakrav/gumae/pbs-jobs/MAGeT.py-executor-1-20150330-102518068191.job
27976498.gpc-sched-ib0
Submitted!
qsub -o MAGeT.py-executor-2-20150330-102609930277.job-o.log -e MAGeT.py-executor-2-20150330-102609930277.job-e.log -V -Wdepend=after:27976493.gpc-sched-ib0 /home/m/mchakrav/gumae/pbs-jobs/MAGeT.py-executor-2-20150330-102609930277.job
27976502.gpc-sched-ib0
Submitted!
qsub: submit error (Invalid Job Dependency)
Traceback (most recent call last):
  File "/project/j/jlerch/matthijs/pydpiper_modules/pydpiper-master-v1.13.1//bin/MAGeT.py", line 4, in <module>
    __import__('pkg_resources').run_script('pydpiper==1.13.1', 'MAGeT.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 517, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1436, in run_script
    exec(code, namespace, namespace)
  File "/scratch/project/j/jlerch/matthijs/pydpiper_modules/pydpiper-master-v1.13.1/python/pydpiper-1.13.1-py2.7.egg/EGG-INFO/scripts/MAGeT.py", line 197, in <module>
    application.start()
  File "/project/j/jlerch/matthijs/pydpiper_modules/pydpiper-master-v1.13.1/python/pydpiper-1.13.1-py2.7.egg/pydpiper/application.py", line 177, in start
    roq.createAndSubmitPbsScripts()
  File "/project/j/jlerch/matthijs/pydpiper_modules/pydpiper-master-v1.13.1/python/pydpiper-1.13.1-py2.7.egg/pydpiper/queueing.py", line 95, in createAndSubmitPbsScripts
    self.createAndSubmitExecutorJobFile(i, time=t, after=serverJobId)
  File "/project/j/jlerch/matthijs/pydpiper_modules/pydpiper-master-v1.13.1/python/pydpiper-1.13.1-py2.7.egg/pydpiper/queueing.py", line 104, in createAndSubmitExecutorJobFile
    self.constructAndSubmitJobFile(execId, time, isMainFile=False, after=after)
  File "/project/j/jlerch/matthijs/pydpiper_modules/pydpiper-master-v1.13.1/python/pydpiper-1.13.1-py2.7.egg/pydpiper/queueing.py", line 81, in constructAndSubmitJobFile
    jobId = self.submitJob(jobName, after, afterany)
  File "/project/j/jlerch/matthijs/pydpiper_modules/pydpiper-master-v1.13.1/python/pydpiper-1.13.1-py2.7.egg/pydpiper/queueing.py", line 180, in submitJob
    out = subprocess.check_output(cmd)
  File "/scinet/gpc/tools/Python/Python278-shared-intel/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['qsub', '-o', 'MAGeT.py-executor-3-20150330-102703346269.job-o.log', '-e', 'MAGeT.py-executor-3-20150330-102703346269.job-e.log', '-V', '-Wdepend=after:27976493.gpc-sched-ib0', '/home/m/mchakrav/gumae/pbs-jobs/MAGeT.py-executor-3-20150330-102703346269.job']' returned non-zero exit status 208

```

**Comment by gdevenyi** [comment]
Followup:

Out of pure luck the pipeline started while it was still being submitted and the executors immediately failed due to another problem.

**Comment by gdevenyi** [comment]
If you're (un)lucky enough to have a very high priority on scinet (say as your allocation window rolls over) Scinet can actually start up pydpiper jobs before the submission has completed.

When this happens this breaks the submitting process (see above) and the executors which can't find a URI.

**Comment by bcdarwin** [comment]
Unable to reproduce this "problem" ...

One possible workaround would be to use `pipeline_executor.py --num-executors=... --uri-file=... ...` most stuff you need should be set in the config file (note: our PydPiper module on SciNet currently sets $PYDPIPER_CONFIG_FILE, so you don't need to specify this in the command), though I haven't tried this so you might need to tweak some flags.

I guess one fix might be to put and remove a hold on the first job somehow ... maybe worth us emailing the SciNet guys?

**Comment by gdevenyi** [comment]
Email in process with scinet, "first world problems" I know...

**Comment by gdevenyi** [comment]
Sorted with Scinet.

Thanks for the info on the config file.
