### ISSUE TITLE
Lost executors in version v1.14-beta

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/pydpiper#216]
Details from Henrik:

[2015-06-29 20:09:15.773,pydpiper.pipeline,INFO] Lost Stage 42: mincblur -clobber -no_apodize -fwhm 0.8 /mousedata/MicroCT/project-DEV_MCT/NXN-MBM/NXN_K1030-15_WT.mnc /mousedata/MicroCT/project-DEV_MCT/NXN-MBM/NXN-MBM_processed/NXN_K1030-15_WT/tmp/NXN_K1030-15_WT_fwhm0.8 -gradient:
[2015-06-29 20:09:15.787,pydpiper.pipeline,INFO] Client un-registered (seppuku!): PYRO:obj_83393c7dc9404eec9ce0a0b66bc06389@192.168.201.97:60697
[2015-06-29 20:09:15.787,pydpiper.pipeline,ERROR] clientURI not found in server client list:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pydpiper-1.14_beta-py2.7.egg/pydpiper/pipeline.py", line 604, in updateClientTimestamp
    self.clients[clientURI].timestamp = t
KeyError: u'PYRO:obj_e8eed47bbd084b69bcf0c2c99da2aabb@192.168.201.97:56515'

[2015-06-29 20:09:15.840,pydpiper.pipeline_executor,ERROR] Heartbeat thread crashed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pydpiper-1.14_beta-py2.7.egg/pydpiper/pipeline_executor.py", line 454, in heartbeat
    self.pyro_proxy_for_server.updateClientTimestamp(self.clientURI, tick)
  File "/usr/lib/python2.7/site-packages/Pyro4-4.38.dev0-py2.7.egg/Pyro4/core.py", line 168, in **call**
    return self.__send(self.__name, args, kwargs)
  File "/usr/lib/python2.7/site-packages/Pyro4-4.38.dev0-py2.7.egg/Pyro4/core.py", line 408, in _pyroInvoke
    raise data
KeyError: u'PYRO:obj_ae61a677d870464cbf020859725e6a53@192.168.201.97:48915'

**Comment by gdevenyi** [comment]
Related to #172 ?

**Comment by mcvaneede** [comment]
Closing for now. Most network related issues we are aware of have been addressed.
