### ISSUE TITLE
pydpiper2: Ctrl-C throws error instead of safely shutting down

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#276]
```
^CProcess Process-2:

KeyboardInterrupt caught: cleaning up, shutting down executors.

Traceback (most recent call last):
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/quarantine/pydpiper/2.0.1/build/lib/python3.5/site-packages/pydpiper-2.0.1-py3.5.egg/pydpiper/execution/pipeline.py", line 1024, in loop
    p.set_shutdown_ev()
  File "/opt/quarantine/pydpiper/2.0.1/build/lib/python3.5/site-packages/Pyro4-4.50-py3.5.egg/Pyro4/core.py", line 171, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/opt/quarantine/pydpiper/2.0.1/build/lib/python3.5/site-packages/Pyro4-4.50-py3.5.egg/Pyro4/core.py", line 422, in _pyroInvoke
    msg = message.Message.recv(self._pyroConnection, [message.MSG_RESULT], hmac_key=self._pyroHmacKey)
  File "/opt/quarantine/pydpiper/2.0.1/build/lib/python3.5/site-packages/Pyro4-4.50-py3.5.egg/Pyro4/message.py", line 167, in recv
    msg = cls.from_header(connection.recv(cls.header_size))
  File "/opt/quarantine/pydpiper/2.0.1/build/lib/python3.5/site-packages/Pyro4-4.50-py3.5.egg/Pyro4/socketutil.py", line 451, in recv
    return receiveData(self.sock, size)
  File "/opt/quarantine/pydpiper/2.0.1/build/lib/python3.5/site-packages/Pyro4-4.50-py3.5.egg/Pyro4/socketutil.py", line 175, in receiveData
    raise err
Pyro4.errors.ConnectionClosedError: receiving: not enough data

```

**Comment by gdevenyi** [comment]
As a consequence of this, jobs aren't deleted from the cluster either.

**Comment by gdevenyi** [comment]
Still a bug on 2.0.10

**Comment by gdevenyi** [comment]
Still the case on 2.0.12
