### ISSUE TITLE
twolevel_model_building ValueError "Usecols do not match names."

### ISSUE THREAD

**Issue by DJFernandes** [Mouse-Imaging-Centre/pydpiper#284]
Two level model raises ValueError("Usecols do not match names.")

Command is located here 
/hpf/largeprojects/MICe/dfernandes/social_behaviour_study/exp1/registration/two_level_pydpyper/cmds.txt

The command ran was the following:

`cd /hpf/largeprojects/MICe/dfernandes/social_behaviour_study/exp1/registration/two_level_pydpyper
module use /hpf/largeprojects/MICe/tools/modulefiles
module load gcc/4.9.1 octave/4.0.0 python/3.5.2 imagemagick/6.8.9-5
module load minc-toolkit/1.9.11 pyminc/0.47 minc-stuffs/0.1.17  pydpiper/2.0.3

twolevel_model_building.py --pipeline-name=exp1 --num-executors=40 --init-model=/hpf/largeprojects/MICe/tools/initial-models/Pydpiper-pride-of-models/p36/p36_MEMRI_mouse_brain.mnc --registration-method=mincANTS --csv-file files.csv`

**Comment by DJFernandes** [comment]
Error generated

`Traceback (most recent call last):
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.3/bin/twolevel_model_building.py", line 4, in <module>
    __import__('pkg_resources').run_script('pydpiper==2.0.3', 'twolevel_model_building.py')
  File "/hpf/largeprojects/MICe/tools/python/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/hpf/largeprojects/MICe/tools/python/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.3/lib/python/pydpiper-2.0.3-py3.5.egg/EGG-INFO/scripts/twolevel_model_building.py", line 250, in <module>
    main(sys.argv)
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.3/lib/python/pydpiper-2.0.3-py3.5.egg/EGG-INFO/scripts/twolevel_model_building.py", line 247, in main
    execute(two_level_pipeline(options).stages, options)
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.3/lib/python/pydpiper-2.0.3-py3.5.egg/EGG-INFO/scripts/twolevel_model_building.py", line 41, in two_level_pipeline
    usecols=['group', 'file'])
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.3/lib/python/pandas-0.19.1-py3.5-linux-x86_64.egg/pandas/io/parsers.py", line 645, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.3/lib/python/pandas-0.19.1-py3.5-linux-x86_64.egg/pandas/io/parsers.py", line 388, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.3/lib/python/pandas-0.19.1-py3.5-linux-x86_64.egg/pandas/io/parsers.py", line 729, in __init__
    self._make_engine(self.engine)
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.3/lib/python/pandas-0.19.1-py3.5-linux-x86_64.egg/pandas/io/parsers.py", line 922, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.3/lib/python/pandas-0.19.1-py3.5-linux-x86_64.egg/pandas/io/parsers.py", line 1433, in __init__
    raise ValueError("Usecols do not match names.")
`

**Comment by bcdarwin** [comment]
We changed the format accepted by the twolevel code from "wide" to "long" format so that you can basically just feed it the CSVs you use for analysis.  So, you give it a CSV having (at least) columns named 'group' and 'file' (and any others).

You're right that the error message and documentation are no good.

**Comment by DJFernandes** [comment]
Fixed
