### ISSUE TITLE
MBM.py without options should give help output

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#292]
Instead:
```sh
Traceback (most recent call last):
  File "/opt/quarantine/pydpiper/2.0.3/build/bin/MBM.py", line 4, in <module>
    __import__('pkg_resources').run_script('pydpiper==2.0.3', 'MBM.py')
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/opt/quarantine/pydpiper/2.0.3/build/lib/python3.5/site-packages/pydpiper-2.0.3-py3.5.egg/EGG-INFO/scripts/MBM.py", line 286, in <module>
    mbm_application()
  File "/opt/quarantine/pydpiper/2.0.3/build/lib/python3.5/site-packages/pydpiper-2.0.3-py3.5.egg/pydpiper/execution/application.py", line 173, in f
    options = parse(p, sys.argv[1:])
  File "/opt/quarantine/pydpiper/2.0.3/build/lib/python3.5/site-packages/pydpiper-2.0.3-py3.5.egg/pydpiper/core/arguments.py", line 185, in parse
    go_2(parser, current_prefix="", current_ns=main_ns)
  File "/opt/quarantine/pydpiper/2.0.3/build/lib/python3.5/site-packages/pydpiper-2.0.3-py3.5.egg/pydpiper/core/arguments.py", line 174, in go_2
    current_ns=ns)
  File "/opt/quarantine/pydpiper/2.0.3/build/lib/python3.5/site-packages/pydpiper-2.0.3-py3.5.egg/pydpiper/core/arguments.py", line 178, in go_2
    if q.cast else current_ns.__dict__[q.namespace])
  File "/opt/quarantine/pydpiper/2.0.3/build/lib/python3.5/site-packages/pydpiper-2.0.3-py3.5.egg/pydpiper/minc/registration.py", line 2191, in to_lsq6_conf
    pride_of_models=lsq6_args.pride_of_models)
  File "/opt/quarantine/pydpiper/2.0.3/build/lib/python3.5/site-packages/pydpiper-2.0.3-py3.5.egg/pydpiper/minc/registration.py", line 2616, in verify_correct_lsq6_target_options
    raise ValueError(no_target_msg)
ValueError: Error: please specify a target for the 6 parameter alignment. Options are: --lsq6-target, --init-model, --bootstrap, and for some pipelines --pride-of-models.
```

**Comment by bcdarwin** [comment]
Fixed in master.
