### ISSUE TITLE
--lsq12-max-pairs doesn't work as expected, error on "None"

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#297]
Help:
```sh
 --lsq12-max-pairs MAX_PAIRS
                        Maximum number of pairs to register together ('None'
                        implies all pairs). [Default = 25]
```

My call:
```sh
--lsq12-max-pairs None
#or
--lsq12-max-pairs 'None'
#or
--lsq12-max-pairs=None
```

Result:
```python
Traceback (most recent call last):
  File "/opt/quarantine/pydpiper/2.0.5/build/bin/MBM.py", line 4, in <module>
    __import__('pkg_resources').run_script('pydpiper==2.0.5', 'MBM.py')
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/opt/quarantine/pydpiper/2.0.5/build/lib/python3.5/site-packages/pydpiper-2.0.5-py3.5.egg/EGG-INFO/scripts/MBM.py", line 286, in <module>
    mbm_application()
  File "/opt/quarantine/pydpiper/2.0.5/build/lib/python3.5/site-packages/pydpiper-2.0.5-py3.5.egg/pydpiper/execution/application.py", line 173, in f
    execute(pipeline(options).stages, options)
  File "/opt/quarantine/pydpiper/2.0.5/build/lib/python3.5/site-packages/pydpiper-2.0.5-py3.5.egg/EGG-INFO/scripts/MBM.py", line 51, in mbm_pipeline
    output_dir=options.application.output_directory))
  File "/opt/quarantine/pydpiper/2.0.5/build/lib/python3.5/site-packages/pydpiper-2.0.5-py3.5.egg/EGG-INFO/scripts/MBM.py", line 137, in mbm
    nlin_conf=full_hierarchy))
  File "/opt/quarantine/pydpiper/2.0.5/build/lib/python3.5/site-packages/pydpiper-2.0.5-py3.5.egg/pydpiper/minc/registration.py", line 2069, in lsq12_nlin_build_model
    lsq12_dir=lsq12_dir))
  File "/opt/quarantine/pydpiper/2.0.5/build/lib/python3.5/site-packages/pydpiper-2.0.5-py3.5.egg/pydpiper/minc/registration.py", line 1993, in lsq12_pairwise
    max_pairs=lsq12_conf.max_pairs))
  File "/opt/quarantine/pydpiper/2.0.5/build/lib/python3.5/site-packages/pydpiper-2.0.5-py3.5.egg/pydpiper/minc/registration.py", line 1892, in multilevel_pairwise_minctracc
    if max_pairs < 2:
TypeError: unorderable types: NoneType() < int()

```

**Comment by bcdarwin** [comment]
fixed in develop
