### ISSUE TITLE
pydpiper 2.0.6 twolevel_model_building.py CSV error

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#329]
Trying to run with the CSV:
```
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom121_002_1_20161101_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom121_102_1_20161119_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom121_003_1_20161101_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom121_103_1_20161119_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom121_004_1_20161101_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom121_104_1_20161119_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom121_005_1_20161101_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom121_105_1_20161119_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom221_006_1_20161101_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom221_106_1_20161119_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom221_007_1_20161101_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom221_107_1_20161119_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom221_008_1_20161101_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom221_108_1_20161119_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom221_009_1_20161101_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom221_109_1_20161119_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom122_001_2_20161123_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom122_101_2_20161210_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom122_002_2_20161123_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom122_102_2_20161210_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom122_004_2_20161123_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom122_104_2_20161210_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom222_005_2_20161123_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom222_105_2_20161210_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom222_006_2_20161123_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom222_106_2_20161210_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom211_001_3_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom211_101_3_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom211_002_3_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom211_102_3_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_003_3_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_103_3_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_004_3_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_104_3_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_005_3_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_105_3_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_006_3_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_106_3_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom211_007_4_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom211_107_4_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom211_008_4_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom211_108_4_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom211_009_4_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom211_109_4_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_010_4_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_110_4_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_011_4_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_111_4_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_012_4_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_112_4_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_013_4_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom111_113_4_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_014_5_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_114_5_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_015_5_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_115_5_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_016_5_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_116_5_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_017_5_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_117_5_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom112_018_5_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom112_118_5_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom112_020_5_20170314_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom112_120_5_20170330_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom122_001_6_20170407_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom122_101_6_20170425_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom122_002_6_20170407_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom122_102_6_20170425_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom122_003_6_20170407_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom122_103_6_20170425_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom222_004_6_20170407_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom222_104_6_20170425_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom222_005_6_20170407_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom222_105_6_20170425_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom222_006_6_20170407_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom222_106_6_20170425_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom222_007_6_20170407_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom222_107_6_20170425_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom222_008_6_20170407_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom222_108_6_20170425_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_001_7_20170411_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_101_7_20170425_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_002_7_20170411_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_102_7_20170425_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_003_7_20170411_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_103_7_20170425_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_004_7_20170411_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom212_104_7_20170425_mri_lsq6.mnc
/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom112_005_7_20170411_mri_lsq6.mnc,/data/chamal/projects/elisa/maternal_infection/preliminary_preprocessed/mch_mom112_105_7_20170425_mri_lsq6.mnc
```

Results in the following error:
```
Traceback (most recent call last):
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/pandas/core/common.py", line 1404, in _asarray_tuplesafe
    result[:] = values
ValueError: could not broadcast input array from shape (0,2) into shape (0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/pandas/core/frame.py", line 2402, in _ensure_valid_index
    value = Series(value)
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/pandas/core/series.py", line 227, in __init__
    raise_cast_failure=True)
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/pandas/core/series.py", line 2922, in _sanitize_array
    subarr = _asarray_tuplesafe(data, dtype=dtype)
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/pandas/core/common.py", line 1407, in _asarray_tuplesafe
    result[:] = [tuple(x) for x in values]
ValueError: cannot copy sequence with size 2 to array axis with dimension 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/quarantine/pydpiper/2.0.6/build/bin/twolevel_model_building.py", line 4, in <module>
    __import__('pkg_resources').run_script('pydpiper==2.0.6', 'twolevel_model_building.py')
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/opt/quarantine/pydpiper/2.0.6/build/lib/python3.5/site-packages/pydpiper-2.0.6-py3.5.egg/EGG-INFO/scripts/twolevel_model_building.py", line 260, in <module>
    main(sys.argv)
  File "/opt/quarantine/pydpiper/2.0.6/build/lib/python3.5/site-packages/pydpiper-2.0.6-py3.5.egg/EGG-INFO/scripts/twolevel_model_building.py", line 257, in main
    execute(two_level_pipeline(options).stages, options)
  File "/opt/quarantine/pydpiper/2.0.6/build/lib/python3.5/site-packages/pydpiper-2.0.6-py3.5.egg/EGG-INFO/scripts/twolevel_model_building.py", line 42, in two_level_pipeline
    .assign(file=lambda df:
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/pandas/core/frame.py", line 2527, in assign
    data[k] = v
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/pandas/core/frame.py", line 2357, in __setitem__
    self._set_item(key, value)
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/pandas/core/frame.py", line 2422, in _set_item
    self._ensure_valid_index(value)
  File "/opt/quarantine/anaconda/4.2.0-python3/build/lib/python3.5/site-packages/pandas/core/frame.py", line 2404, in _ensure_valid_index
    raise ValueError('Cannot set a frame with no defined index '
ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series
```

**Comment by bcdarwin** [comment]
What happens if you give the column the name 'file' in the csv?

**Comment by gdevenyi** [comment]
I have two columns, do I do both?

**Comment by bcdarwin** [comment]
Oh, I see ... so as of 2.x the twolevel takes a 'long' rather than 'wide' csv, i.e. one row per file (partly because although it's easy to reshape via dplyr/tidyr, we found that users most often had csvs in the other format and had to convert; also this way lets you add masks and potentially initial xfms)

**Comment by bcdarwin** [comment]
For the twolevel, you specify the first-level groupings via a 'group' column with some identifier.

**Comment by gdevenyi** [comment]
Oh, okay.

We're using this longitudinally, does this mean I need one group per subject?

**Comment by bcdarwin** [comment]
That's probably a safe option.

**Comment by gdevenyi** [comment]
Okay, so I'm not getting how this works. I have subjects with longitudinal timepoints, how is this CSV supposed to look?

**Comment by bcdarwin** [comment]
file,group
subj_1_timepoint_1.mnc,1
subj_2_timepoint_2.mnc,2
subj_2_timepoint_1.mnc,2
subj_1_timepoint_2.mnc,1
...
