### ISSUE TITLE
Running MAGeT.py without option produces error instead of help

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#346]
```sh
$ MAGeT.py 
Traceback (most recent call last):
  File "/opt/quarantine/pydpiper/2.0.8/install/bin/MAGeT.py", line 4, in <module>
    __import__('pkg_resources').run_script('pydpiper==2.0.8', 'MAGeT.py')
  File "/opt/quarantine/anaconda/5.0.1-python3/install/lib/python3.6/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/quarantine/anaconda/5.0.1-python3/install/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/opt/quarantine/pydpiper/2.0.8/install/lib/python3.6/site-packages/pydpiper-2.0.8-py3.6.egg/EGG-INFO/scripts/MAGeT.py", line 432, in <module>
    maget_application()
  File "/opt/quarantine/pydpiper/2.0.8/install/lib/python3.6/site-packages/pydpiper-2.0.8-py3.6.egg/pydpiper/execution/application.py", line 173, in f
    execute(pipeline(options).stages, options)
  File "/opt/quarantine/pydpiper/2.0.8/install/lib/python3.6/site-packages/pydpiper-2.0.8-py3.6.egg/EGG-INFO/scripts/MAGeT.py", line 374, in maget_pipeline
    imgs = get_imgs(options.application)
  File "/opt/quarantine/pydpiper/2.0.8/install/lib/python3.6/site-packages/pydpiper-2.0.8-py3.6.egg/EGG-INFO/scripts/MAGeT.py", line 55, in get_imgs
    return imgs
UnboundLocalError: local variable 'imgs' referenced before assignment

```

**Comment by gdevenyi** [comment]
```
$ MBM.py

Warning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88 [/opt/quarantine/anaconda/5.1.0-python3/install/lib/python3.6/importlib/_bootstrap.py:219]


Warning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__ [/opt/quarantine/anaconda/5.1.0-python3/install/lib/python3.6/importlib/_bootstrap.py:219]


Warning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88 [/opt/quarantine/anaconda/5.1.0-python3/install/lib/python3.6/importlib/_bootstrap.py:219]


Warning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__ [/opt/quarantine/anaconda/5.1.0-python3/install/lib/python3.6/importlib/_bootstrap.py:219]

Traceback (most recent call last):
  File "/opt/quarantine/pydpiper/2.0.12/install/bin/MBM.py", line 4, in <module>
    __import__('pkg_resources').run_script('pydpiper==2.0.12', 'MBM.py')
  File "/opt/quarantine/anaconda/5.1.0-python3/install/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/quarantine/anaconda/5.1.0-python3/install/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/opt/quarantine/pydpiper/2.0.12/install/lib/python3.6/site-packages/pydpiper-2.0.12-py3.6.egg/EGG-INFO/scripts/MBM.py", line 532, in <module>
    mbm_application()
  File "/opt/quarantine/pydpiper/2.0.12/install/lib/python3.6/site-packages/pydpiper-2.0.12-py3.6.egg/pydpiper/execution/application.py", line 205, in f
    options = parse(p, sys.argv[1:])
  File "/opt/quarantine/pydpiper/2.0.12/install/lib/python3.6/site-packages/pydpiper-2.0.12-py3.6.egg/pydpiper/core/arguments.py", line 212, in parse
    go_2(parser, current_prefix="", current_ns=main_ns)
  File "/opt/quarantine/pydpiper/2.0.12/install/lib/python3.6/site-packages/pydpiper-2.0.12-py3.6.egg/pydpiper/core/arguments.py", line 191, in go_2
    current_ns=ns)
  File "/opt/quarantine/pydpiper/2.0.12/install/lib/python3.6/site-packages/pydpiper-2.0.12-py3.6.egg/pydpiper/core/arguments.py", line 197, in go_2
    if q.cast else current_ns.__dict__[q.namespace])
  File "/opt/quarantine/pydpiper/2.0.12/install/lib/python3.6/site-packages/pydpiper-2.0.12-py3.6.egg/pydpiper/minc/registration.py", line 2216, in to_lsq6_conf
    pride_of_models=lsq6_args.pride_of_models)
  File "/opt/quarantine/pydpiper/2.0.12/install/lib/python3.6/site-packages/pydpiper-2.0.12-py3.6.egg/pydpiper/minc/registration.py", line 2650, in verify_correct_lsq6_target_options
    raise ValueError(no_target_msg)
ValueError: Error: please specify a target for the 6 parameter alignment. Options are: --lsq6-target, --init-model, --bootstrap, and for some pipelines --pride-of-models.

```
