### ISSUE TITLE
MAGeT bug: Don't call atlases "atlas"

### ISSUE THREAD

**Issue by DJFernandes** [Mouse-Imaging-Centre/pydpiper#351]
Noticed a little bug/feature of MAGeT (in both pydpiper/2.0.8 and 2.0.9). It doesn't like it when you call an atlas in your atlas library 'atlas'.

In the directory "/hpf/largeprojects/MICe/dfernandes/lqiu_long_redone/atlas/MAGeT_2017/report_atlas_bug/atlas_test", I have the files: atlas_average.mnc , atlas_labels.mnc,  atlas_mask.mnc
In the directory "/hpf/largeprojects/MICe/dfernandes/lqiu_long_redone/atlas/MAGeT_2017/report_atlas_bug/atlas_test2", I have the files: X_average.mnc, X_labels.mnc, X_mask.mnc

They are exactly the same files, but with different names.

Running the command
`MAGeT.py --atlas-library=atlas_test --lsq12-protocol=/hpf/largeprojects/MICe/tools/protocols/linear/default_linear_MAGeT_prot.csv --nlin-protocol=/hpf/largeprojects/MICe/tools/protocols/nonlinear/default_nlin_MAGeT_minctracc_prot.csv --masking-nlin-protocol=/hpf/largeprojects/MICe/tools/protocols/nonlinear/default_nlin_MAGeT_minctracc_prot.csv --num-executors=100 --registration-method=minctracc --max-templates=20 --files /hpf/largeprojects/MICe/dfernandes/lqiu_long_redone/lvl1reg/p65/p65_processed/*/resampled/*_nuc_inorm_lsq6.mnc `

I get the error:
`Traceback (most recent call last):
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.9/bin/MAGeT.py", line 4, in <module>
    __import__('pkg_resources').run_script('pydpiper==2.0.9', 'MAGeT.py')
  File "/hpf/largeprojects/MICe/tools/python/3.6.2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/hpf/largeprojects/MICe/tools/python/3.6.2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.9/lib/python/pydpiper-2.0.9-py3.6.egg/EGG-INFO/scripts/MAGeT.py", line 432, in <module>
    maget_application()
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.9/lib/python/pydpiper-2.0.9-py3.6.egg/pydpiper/execution/application.py", line 173, in f
    execute(pipeline(options).stages, options)
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.9/lib/python/pydpiper-2.0.9-py3.6.egg/EGG-INFO/scripts/MAGeT.py", line 380, in maget_pipeline
    output_dir=options.application.output_directory)
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.9/lib/python/pydpiper-2.0.9-py3.6.egg/EGG-INFO/scripts/MAGeT.py", line 249, in maget
    pipeline_sub_dir=pipeline_sub_dir)
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.9/lib/python/pydpiper-2.0.9-py3.6.egg/EGG-INFO/scripts/MAGeT.py", line 218, in atlases_from_dir
    atlas_library = read_atlas_dir(atlas_lib=atlas_lib, pipeline_sub_dir=pipeline_sub_dir)
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.9/lib/python/pydpiper-2.0.9-py3.6.egg/EGG-INFO/scripts/MAGeT.py", line 75, in read_atlas_dir
    return process_atlas_files(glob.iglob(os.path.join(atlas_lib, "*.mnc")), pipeline_sub_dir=pipeline_sub_dir)
  File "/hpf/largeprojects/MICe/tools/pydpiper/2.0.9/lib/python/pydpiper-2.0.9-py3.6.egg/EGG-INFO/scripts/MAGeT.py", line 96, in process_atlas_files
    raise ValueError("atlas filename conventions are wrong for atlas '%s'" % group)
ValueError: atlas filename conventions are wrong for atlas 'atlas_test/at'`

Running the command below (with atlas_test2) has expected behaviour:
`MAGeT.py --atlas-library=atlas_test2 --lsq12-protocol=/hpf/largeprojects/MICe/tools/protocols/linear/default_linear_MAGeT_prot.csv --nlin-protocol=/hpf/largeprojects/MICe/tools/protocols/nonlinear/default_nlin_MAGeT_minctracc_prot.csv --masking-nlin-protocol=/hpf/largeprojects/MICe/tools/protocols/nonlinear/default_nlin_MAGeT_minctracc_prot.csv --num-executors=100 --registration-method=minctracc --max-templates=20 --files /hpf/largeprojects/MICe/dfernandes/lqiu_long_redone/lvl1reg/p65/p65_processed/*/resampled/*_nuc_inorm_lsq6.mnc`

I don't know if the error from using the name 'atlas' is expected but it is there and easy to avoid if you are aware of it.

**Comment by bcdarwin** [comment]
This is #323 again :(
