### ISSUE TITLE
--output-dir flag breaks anything that calls create_quality_control_images

### ISSUE THREAD

**Issue by nzxwang** [Mouse-Imaging-Centre/pydpiper#373]
It seems that if you use --output-dir, the `create_quality_control_images` function will get caught on `ensure_output_paths_in_dir`.

`/hpf/largeprojects/MICe/nwang/LSQ6_try$ LSQ6.py --pipeline-name LSQ6_try_zflip --num-executors 4 --lsq6-large-rotations --init-model /hpf/largeprojects/MICe/nwang/tools/Allen-Brain/Allen_50micron_average.mnc --files /hpf/largeprojects/MICe/nwang/TV_MBM_nomaget/TV_nlin/nlin-3_zflip.mnc --output-dir /hpf/largeprojects/MICe/nwang/LSQ6_try/output

Warning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88 [/axiom2/projects/software/arch/linux-xenial-xerus/python/3.6.4/lib/python3.6/importlib/_bootstrap.py:219]

Warning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__ [/axiom2/projects/software/arch/linux-xenial-xerus/python/3.6.4/lib/python3.6/importlib/_bootstrap.py:219]

Warning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88 [/axiom2/projects/software/arch/linux-xenial-xerus/python/3.6.4/lib/python3.6/importlib/_bootstrap.py:219]

Warning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__ [/axiom2/projects/software/arch/linux-xenial-xerus/python/3.6.4/lib/python3.6/importlib/_bootstrap.py:219]

Traceback (most recent call last):
  File "/hpf/largeprojects/MICe/nwang/venvs/MICe-lab/bin/LSQ6.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/micehome/nwang/repos/pydpiper/pydpiper/pipelines/LSQ6.py", line 77, in <module>
    lsq6_application()
  File "/micehome/nwang/repos/pydpiper/pydpiper/execution/application.py", line 196, in f
    execute(pipeline(options).stages, options)
  File "/micehome/nwang/repos/pydpiper/pydpiper/execution/application.py", line 147, in execute
    ensure_output_paths_in_dir(stages, options.application.output_directory)
  File "/micehome/nwang/repos/pydpiper/pydpiper/execution/application.py", line 81, in ensure_output_paths_in_dir
    "pipeline directory %s" % (o.path, s, d))
ValueError: output Allen_50micron_average_50micron_resampled/tmp/Allen_50micron_average_50micron_resampled_fwhm0.25_blur.mnc of stage <pydpiper.core.stages.CmdStage object at 0x7f81892f7898> not contained inside pipeline directory /hpf/largeprojects/MICe/nwang/LSQ6_try/output`

**Comment by nzxwang** [comment]
/hpf/largeprojects/MICe/nwang/TV_MBM_magetANTS$ MBM.py --resolution 0.05 --pipeline-name=TV --no-run-maget --maget-no-mask --no-common-space-registration --subject-matter mousebrain --num-executors 1000 --time 48:00:00 --lsq6-centre-estimation --bootstrap --nuc --no-inormalize --lsq12-protocol /hpf/largeprojects/MICe/tools/protocols/linear/Pydpiper_testing_default_lsq12.csv --files /hpf/largeprojects/MICe/nwang/TV_MBM_magetANTS/files/F_01_smooth_padded.mnc /hpf/largeprojects/MICe/nwang/TV_MBM_magetANTS/files/F_02_smooth_padded.mnc /hpf/largeprojects/MICe/nwang/TV_MBM_magetANTS/files/F_03_smooth_padded.mnc /hpf/largeprojects/MICe/nwang --output-dir /hpf/largeprojects/MICe/nwang/TV_MBM_magetANTS/output

Warning: Not masking your images from atlas masks after LSQ6 alignment ... probably not what you want (this can have negative effects on your registration and statistics) [/micehome/nwang/repos/pydpiper/pydpiper/pipelines/MBM.py:297]

Traceback (most recent call last):
  File "/hpf/largeprojects/MICe/nwang/venvs/MICe-lab/bin/MBM.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/micehome/nwang/repos/pydpiper/pydpiper/pipelines/MBM.py", line 510, in <module>
    mbm_application()
  File "/micehome/nwang/repos/pydpiper/pydpiper/execution/application.py", line 196, in f
    execute(pipeline(options).stages, options)
  File "/micehome/nwang/repos/pydpiper/pydpiper/execution/application.py", line 147, in execute
    ensure_output_paths_in_dir(stages, options.application.output_directory)
  File "/micehome/nwang/repos/pydpiper/pydpiper/execution/application.py", line 81, in ensure_output_paths_in_dir
    "pipeline directory %s" % (o.path, s, d))
ValueError: output F_01_smooth_padded_50micron_resampled/tmp/F_01_smooth_padded_50micron_resampled_fwhm4.5_blur.mnc of stage <pydpiper.core.stages.CmdStage object at 0x7f53a38c69e8> not contained inside pipeline directory /hpf/largeprojects/MICe/nwang/TV_MBM_magetANTS/output

**Comment by nzxwang** [comment]
this is also closed by c63cd20
