### ISSUE TITLE
pydpiper 2.0.12 pipeline_executor.py fails if PYDPIPER_CONFIG_FILE is undefined in environment

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#394]
```
Traceback (most recent call last):
	  File "/opt/quarantine/pydpiper/2.0.12/install/bin/pipeline_executor.py", line 4, in <module>
	    __import__('pkg_resources').run_script('pydpiper==2.0.12', 'pipeline_executor.py')
	  File "/opt/quarantine/anaconda/5.1.0-python3/install/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
	    self.require(requires)[0].run_script(script_name, ns)
	  File "/opt/quarantine/anaconda/5.1.0-python3/install/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1527, in run_script
	    exec(code, namespace, namespace)
	  File "/opt/quarantine/pydpiper/2.0.12/install/lib/python3.6/site-packages/pydpiper-2.0.12-py3.6.egg/EGG-INFO/scripts/pipeline_executor.py", line 675, in <module>
	    main()
	  File "/opt/quarantine/pydpiper/2.0.12/install/lib/python3.6/site-packages/pydpiper-2.0.12-py3.6.egg/EGG-INFO/scripts/pipeline_executor.py", line 631, in main
	    raise ValueError("PYDPIPER_CONFIG_FILE does not exist in your bash environment!")
	ValueError: PYDPIPER_CONFIG_FILE does not exist in your bash environment!

```

**Comment by gdevenyi** [comment]
Overly aggressive solution to #372 ?

**Comment by gdevenyi** [comment]
Works okay if I export an empty variable.

**Comment by bcdarwin** [comment]
Fixed in develop.
