### ISSUE TITLE
pydpiper/2.0.12 twolevel_model_building.py fails to start with --no-run-maget

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#400]
```
twolevel_model_building.py --verbose --pipeline-name=twoleveltest \
--no-run-maget \
--csv-file paths_ID.csv \
  --num-executors 350 \
  --output-dir testoutputdir \
  --resolution 0.1 \
  --subject-matter mousebrain \
  --queue-type sge \
  --check-input-files \
  --check-outputs \
  --init-model /opt/quarantine/resources/Dorr_2008_Steadman_2013_Ullmann_2013_Richards_2011_Qiu_2016_Egan_2015_40micron/ex-vivo/DSURQE_40micron.mnc \
  --lsq6-large-rotations-parameters mousebrain \
  --lsq12-protocol /opt/quarantine/pydpiper/2.0.12/src/pydpiper-2.0.12/applications_testing/test_data/minctracc_example_linear_protocol.csv \
  --no-nuc \
  --maget-atlas-library /opt/quarantine/resources/Dorr_2008_Steadman_2013_Ullmann_2013_Richards_2011_Qiu_2016_Egan_2015_40micron/ex-vivo \
  --maget-masking-method minctracc \
  --maget-registration-method minctracc \
  --maget-masking-nlin-protocol /opt/quarantine/pydpiper/2.0.12/src/pydpiper-2.0.12/applications_testing/test_data/default_nlin_MAGeT_minctracc_prot.csv \
  --maget-nlin-protocol /opt/quarantine/pydpiper/2.0.12/src/pydpiper-2.0.12/applications_testing/test_data/default_nlin_MAGeT_minctracc_prot.csv
```

```
Traceback (most recent call last):
  File "/opt/quarantine/pydpiper/2.0.12/install/bin/twolevel_model_building.py", line 4, in <module>
    __import__('pkg_resources').run_script('pydpiper==2.0.12', 'twolevel_model_building.py')
  File "/opt/quarantine/anaconda/5.1.0-python3/install/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/quarantine/anaconda/5.1.0-python3/install/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/opt/quarantine/pydpiper/2.0.12/install/lib/python3.6/site-packages/pydpiper-2.0.12-py3.6.egg/EGG-INFO/scripts/twolevel_model_building.py", line 298, in <module>
    main(sys.argv)
  File "/opt/quarantine/pydpiper/2.0.12/install/lib/python3.6/site-packages/pydpiper-2.0.12-py3.6.egg/EGG-INFO/scripts/twolevel_model_building.py", line 295, in main
    execute(two_level_pipeline(options).stages, options)
  File "/opt/quarantine/pydpiper/2.0.12/install/lib/python3.6/site-packages/pydpiper-2.0.12-py3.6.egg/EGG-INFO/scripts/twolevel_model_building.py", line 58, in two_level_pipeline
    pipeline = two_level(grouped_files_df=files_df, options=options)
  File "/opt/quarantine/pydpiper/2.0.12/install/lib/python3.6/site-packages/pydpiper-2.0.12-py3.6.egg/EGG-INFO/scripts/twolevel_model_building.py", line 204, in two_level
    for x in pd.concat([namespace.maget_result for namespace in first_level_results.build_model])])
  File "/opt/quarantine/pydpiper/2.0.12/install/lib/python3.6/site-packages/pydpiper-2.0.12-py3.6.egg/EGG-INFO/scripts/twolevel_model_building.py", line 204, in <listcomp>
    for x in pd.concat([namespace.maget_result for namespace in first_level_results.build_model])])
AttributeError: 'Namespace' object has no attribute 'maget_result'

```

**Comment by bcdarwin** [comment]
Fixed in develop.
