### ISSUE TITLE
scinet error for failed stages

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/pydpiper#53]
When running on scinet, the following error is raised when a pipeline stage fails. 

2013-05-13 00:42:26,490 __main__ INFO: Stage 590 finished, return was: -9
2013-05-13 00:42:26,537 __main__ ERROR: Error communicating to server in runStage. Error raised to calling thread in launchExecutor. 
Traceback (most recent call last):
  File "/home/j/jlerch/mfriedel/bin/pipeline_executor.py", line 54, in runStage
    p.setStageFailed(i)
  File "/home/j/jlerch/mfriedel/lib/python/Pyro-3.15-py2.7.egg/Pyro/core.py", line 381, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/home/j/jlerch/mfriedel/lib/python/Pyro-3.15-py2.7.egg/Pyro/core.py", line 456, in _invokePYRO
    return self.adapter.remoteInvocation(name, Pyro.constants.RIF_VarargsAndKeywords, vargs, kargs)
  File "/home/j/jlerch/mfriedel/lib/python/Pyro-3.15-py2.7.egg/Pyro/protocol.py", line 457, in remoteInvocation
    return self._remoteInvocation(method, flags, *args)
  File "/home/j/jlerch/mfriedel/lib/python/Pyro-3.15-py2.7.egg/Pyro/protocol.py", line 532, in _remoteInvocation
    answer.raiseEx()
  File "/home/j/jlerch/mfriedel/lib/python/Pyro-3.15-py2.7.egg/Pyro/errors.py", line 72, in raiseEx
    raise self.excObj
AttributeError: 'module' object has no attribute 'dfs_successor'

I believe this could be due to a discrepancy in the version of the networkx library installed on scinet vs. what is installed at MICe. 

This needs to be fixed because it appears to cause the pipeline to not finish properly. e.g. The executor will keep running even though there are no remaining stages. The failed stages need to be properly counted as complete.

**Comment by jasonlerch** [comment]
Fixed
